version: "3"
services:
  time-tracker-db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=time_tracker
      - POSTGRES_PASSWORD=super-secret-pass

  authorization-server:
    image: jboss/keycloak:8.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_IMPORT=/tmp/dev-realm.json
    volumes:
      - ./keycloak-realm/time-tracker-realm.json:/tmp/dev-realm.json

  time-tracker-api:
    image: dovydasvenckus/time-tracker-api
    environment:
      - ACTIVE_PROFILES=prod
      - DB_URL=jdbc:postgresql://time-tracker-db/time_tracker
      - DB_USERNAME=time_tracker
      - DB_PASSWORD=super-secret-pass
      - DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - CORS_ALLOW=
      - AUTH_ISSUER_URI=http://localhost/auth/realms/time-tracker
      - AUTH_KEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmkdhWuJnBf5bhgPZwmKeliGZWoZYUAatbJuyfHk9UUArkJLUbsdtwBcgNC1s8GtQW+M8OJnrThH7E/19CUS0iaIvP5G4d/H3UVn10y7Xlq3lyDOK3pUiWGmvLgQNUOwNsooijcjj3JxmhLesAni3GShrtHYiWpzqFwauOFpEaPmYYeZgPa+qn9pzxh/jv4IFsYxpFCNEncv8mtqcP2VTy4HwEqbbncrpoKE7x2P5Qn2C6oVkKO10efCqBJ3X217Frexa8/JiMb/2qLsvLYY3ae4g0BlDR+e5HFVSXcwF3Zl6R2NkN32znbeZm8ByIm+gDVVhm6j6E7KSsHRNdNFrsQIDAQAB-----END PUBLIC KEY-----

  time-tracker-web:
    image: dovydasvenckus/time-tracker-web
    environment:
      - TIME_TRACKER_AUTH_URL=http://localhost/auth/realms/time-tracker/protocol/openid-connect
      - TIME_TRACKER_AUTH_CLIENT_ID=time-tracker-api
      - TIME_TRACKER_AUTH_REDIRECT_URL=http://localhost/login-oidc
      - TIME_TRACKER_AUTH_SILENT_REDIRECT_URL=http://localhost/silent-renew
      - TIME_TRACKER_AUTH_LOGOFF_REDIRECT_URL=http://localhost/logout-callback
      - TIME_TRACKER_AUTH_JWT_ISSUER=http://localhost/auth/realms/time-tracker

  time-tracker-reverse-proxy:
    image: nginx:1.15-alpine
    depends_on:
      - authorization-server
    ports:
      - "80:80"
    volumes:
      - ./../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wait-for.sh:/tmp/wait-for.sh:ro
    command:
      [
        "/bin/sh",
        "-c",
        '/tmp/wait-for.sh -t 120 authorization-server:8080 && nginx -g "daemon off;"',
      ]
