version: "3"
services:
  time-tracker-api:
    image: dovydasvenckus/time-tracker-api
    restart: always
    env_file:
      - $PWD/../../time-tracker-api.env

  time-tracker-web:
    image: dovydasvenckus/time-tracker-web
    restart: always
  
  time-tracker-reverse-proxy:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - $PWD/../nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    external:
      name: time-tracker-net
