version: "3"
services:
  time-tracker-api:
    image: dovydasvenckus/time-tracker-api
    env_file:
      - $PWD/../../time-tracker-api.env
    deploy:
      resources:
        limits:
          memory: 198M
    restart_policy:
      condition: on-failure
      delay: 60s
      max_attempts: 3

  time-tracker-web:
    image: dovydasvenckus/time-tracker-web
    deploy:
      resources:
        limits:
          memory: 32M
  
  time-tracker-reverse-proxy:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - $PWD/../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 32M
