version: "3"
services:
  time-tracker-db:
    image: postgres:11-alpine
    depends_on:
      - time-tracker_default
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - $PWD/../../time-tracker-db.env
    deploy:
      resources:
        limits:
          memory: 32M

  time-tracker-api:
    image: dovydasvenckus/time-tracker-api
    depends_on:
      - time-tracker-db
    env_file:
      - $PWD/../../time-tracker-api.env
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3

  time-tracker-web:
    image: dovydasvenckus/time-tracker-web
    deploy:
      resources:
        limits:
          memory: 32M

  time-tracker-reverse-proxy:
    image: nginx:1.15-alpine
    volumes:
      - $PWD/../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - $PWD/../../time-tracker-reverse-proxy.env
    deploy:
      resources:
        limits:
          memory: 32M

volumes:
  db-data:

networks:
  default:
    external:
      name: internal-proxy
