version: "3"
services:
  time-tracker-db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - $PWD/../../time-tracker-db.env
    deploy:
      resources:
        limits:
          memory: 64M

  time-tracker-api:
    image: dovydasvenckus/time-tracker-api
    depends_on:
      - time-tracker-db
    env_file:
      - $PWD/../../time-tracker-api.env
    deploy:
      resources:
        limits:
          memory: 384M
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3

  time-tracker-web:
    image: dovydasvenckus/time-tracker-web
    env_file: $PWD/../../time-tracker-web.env
    deploy:
      resources:
        limits:
          memory: 32M

  time-tracker-reverse-proxy:
    image: nginx:1.15-alpine
    expose:
      - 80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - $PWD/../../time-tracker-reverse-proxy.env
    deploy:
      resources:
        limits:
          memory: 64M
    healthcheck:
      test: curl -sS http://authorization-service:8080/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 5

volumes:
  db-data:

networks:
  default:
    external:
      name: internal-proxy
